name: CI - Distzilla

on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  perl-job:
    steps:
      - uses: perlbot/action-dzil@latest
        env:
          EXTRA_DEPS: ""
